services:
  - type: web
    name: phish-capture-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: ROOT_DRIVE_FOLDER_ID
        value: https://drive.google.com/drive/folders/1nhmmHQwbk_95GuqxrE4t56DKL66Mi4Vm?usp=drive_link        # <-- from step 3
      - key: REDIRECT_URI
        value: https://cat-phish.onrender.com/oauth2callback
